baseURL = "http://jscholes.net/"
languageCode = "en-gb"
title = "James Scholes"
disableRSS = true
publishdir = "site"

[params]
    description = "Personal project website and blog of James Scholes, an independent programmer from West Yorkshire"
    tagline = "Personal projects"
    author = "James Scholes"
